### ISSUE TITLE
HidDeviceStream fails to open: Wacom CTL-480 on Windows

### ISSUE THREAD

**Issue by InfinityGhost** [InfinityGhost/OpenTabletDriver#2]
```
Exception has occurred: CLR/HidSharp.Exceptions.DeviceIOException
An unhandled exception of type 'HidSharp.Exceptions.DeviceIOException' occurred in HidSharp.dll: 'Unable to open HID class device (\\?\hid#vid_056a&pid_030e&mi_02#8&123e7efa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}).'
   at HidSharp.Platform.Windows.WinHidStream.Init(String path)
   at HidSharp.Platform.Windows.WinHidDevice.OpenDeviceDirectly(OpenConfiguration openConfig)
   at HidSharp.Device.OpenDeviceAndRestrictAccess(OpenConfiguration openConfig)
   at HidSharp.Device.Open(OpenConfiguration openConfig)
   at HidSharp.Device.Open()
   at HidSharp.HidDevice.Open()
```

**Comment by InfinityGhost** [comment]
# Update
I posted this issue on the HidSharp forum, and got a response from the main developer

>### **Zer**
>Re: HidSharp.Exceptions.DeviceIOException on HidDevice.Open, Windows only
>If it shows up to the OS as a mouse or keyboard, FWIW, Windows will block access to it for "security".

So this likely means that I'll have to look into a separate solution for windows altogether.
