### ISSUE TITLE
DeviceIOException:Error with Huion H640P

### ISSUE THREAD

**Issue by nixls** [InfinityGhost/OpenTabletDriver#755]
## Description

Having my tablet, a Huion H640P, and starting the driver prints a lot of [ArgumentOutOfRangeException:Error] in the console while the driver tries to detect the tablet. I'm attaching the driver log and `lsusb -v` output.
I removed default drivers with `rmmod` before running the driver.
[otd.log](https://github.com/InfinityGhost/OpenTabletDriver/files/5924423/otd.log)
[lsusb.log](https://github.com/InfinityGhost/OpenTabletDriver/files/5924424/lsusb.log)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Artix Linux |
| Software Version | v0.5.1 |
| Tablet           | Huion H640P |

**Comment by nixls** [comment]
Okay, turns out the module loaded itself again. Altho there is another issue with Huion H640P. I'm posting the new log.

```
[Detect:Info]   Searching for tablet 'Huion H640P'
[DeviceIOException:Error]       Unnamed product.
   at HidSharp.Platform.Linux.LinuxHidDevice.GetProductName()
   at HidSharp.HidDevice.GetFriendlyName()
   at OpenTabletDriver.Driver.InitializeDigitizerDevice(HidDevice tabletDevice, DigitizerIdentifier tablet, IReportParser`1 reportParser) in /home/nikig/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver/Driver.cs:line 158
   at OpenTabletDriver.Driver.TryMatchDigitizer(TabletConfiguration config, DigitizerIdentifier& digitizerIdentifier) in /home/nikig/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver/Driver.cs:line 110
   ```

[newotd.log](https://github.com/InfinityGhost/OpenTabletDriver/files/5924477/newotd.log)
